Feature/add basic cli
JSONPath-Plus/JSONPath pull request #206
Opened 2024-03-03 12:51 UTC by vid

## PR description

Adds a basic command line interface. No tests are provided since it just invokes the tested lib and we aren't here to test the runtime.

## Checklist

- [ x] - Added tests
- [ x] - Ran `npm test`, ensuring linting passes
- [x ] - Adjust README documentation if relevant

2024-03-03 18:55 UTC, brettz9 requested changes
I think with the suggested changes and an update to the build file, we'd be ready.

2024-03-03 18:55 UTC, brettz9 commented on src/jsonp-cli.js
> +    // eslint-disable-next-line no-console
```suggestion
    // eslint-disable-next-line no-console -- CLI
```

Like to always give a reason for disabling...

2024-03-03 18:55 UTC, brettz9 commented on src/jsonp-cli.js
> +    console.log("result", result);
```suggestion
    console.log(result);
```

I think by removing the "result" string, a user could more easily pipe the results into a file or something...

2024-03-03 18:55 UTC, brettz9 commented on package.json
> +    "jsonp-cli": "./dist/jsonp-cli.js"
```suggestion
    "jsonp-cli": "./dist/jsonp-cli.js",
    "jsonpath": "./dist/jsonp-cli.js"
```

I think it's easier to remember with at least one more directly evoking the package name

2024-03-03 23:41 UTC, vid commented
Hi, makes sense. I think it's better not to have two bin options so went with the original package name, but happy to make further improvements. Thanks!

2024-03-04 18:45 UTC, brettz9 commented
I'm thinking maybe we should add a `jsonpath-plus` binary too so that people can use the package name (as you originally did in the docs), as well as the shorter `jsonpath`.

2024-03-04 19:29 UTC, vid commented
Oh you're right, I just added the package name as a bin mapping.

2024-03-04 22:55 UTC, brettz9 commented
I changed to avoid a dist file (I think CLI users can generally use the latest version) and linted the file. If you want to take a look, I think it should be ready after that.

2024-03-05 12:08 UTC, vid commented
Makes sense. For completeness (…) I added a `files` directive.

2024-03-05 12:56 UTC, brettz9 requested changes

2024-03-05 12:59 UTC, vid commented
Oh! I wasn't aware of that approach, reverted now.

2024-03-05 13:03 UTC, brettz9 commented
So do the changes I added look ok?

2024-03-05 13:04 UTC, vid commented
Yes, it all "lgtm." Thanks!

2024-03-05 13:05 UTC, brettz9 approved these changes

2024-03-05 13:07 UTC, merged

2024-03-05 13:34 UTC, brettz9 commented
Thanks for the PR! Released as part of v8.1.0

2024-03-05 14:40 UTC, vid commented
Thanks for guiding me through it.